### ISSUE TITLE
Oczy zamknięte i otwarte - praca domowa

### ISSUE THREAD

**Issue by olaartych** [mmagnuski/Analiza-Sygnalu-2017#1]
Jakie wartości mamy przyjąć do pracy domowej z notebook'a zajecia_04 dla oczu zamkniętych i otwartych?
Czy: 
Zamknięte = 11.24- 41.42 
Otwarte=76,33 + 30

**Comment by mmagnuski** [comment]
Ważne aby było zgodne z czasami, które Wam pokazywałem w prezentacji, której, jak właśnie widzę chyba Wam nie udostępniłem...
Ok, dzisiaj wrzucę.

**Comment by pbarkowski** [comment]
Mikołaj, czy to zadanie jest do zrobienia na najbliższe zajęcia, samodzielnie z notebooka?
Czy też (ponieważ ostatnio nie skończyliśmy wszystkiego) na kolejny tydzień?

**Comment by mmagnuski** [comment]
Powiedzmy, że dam Wam czas do końca tygodnia. Zrobię jutro na platformie okienko do zamieszczania prac domowych.

**Comment by mmagnuski** [comment]
BTW - wrzuciłem właśnie prezentacje.

**Comment by diathermy** [comment]
Mikołaj, gdzie mamy przesyłać pracę domową? Na elearningu nie ma okienka. Jeśli na mejla, to jaki tytuł?

**Comment by mswierzewski** [comment]
Wyświetlenie topografii dla alfy podczas zamkniętych i otwartych oczu wydaje mi się, że zrobiłem dobrze na podstawie notebooka. 
![image](https://user-images.githubusercontent.com/23728145/32891388-a809c520-cad2-11e7-9c1f-a635a7838ce4.png)
![image](https://user-images.githubusercontent.com/23728145/32891396-adf411d4-cad2-11e7-8949-8518afa71a6f.png)

Tak już wyświetlenie różnicy topografii pomiędzy zamkniętymi - otwartymi oraz wyświetlenie różnicy zlogarytmizowanych danych jest dla mnie nie jasne. Przykład tego, jak to zrobić jest w notebooku? Czy powinienem się odwołać może jakiś innych materiałów?

**Comment by mmagnuski** [comment]
@diathermy powinno być od wczoraj czy przedwczoraj okienko na e-learningu.
@mswierzewski różnicę dla dwóch wektorów robimy tak samo jak dla dwóch liczb: `topografia_1 - topografia_2`, logarytmizację możemy, tak jak w notebook'u z pracą domową na githubie - `np.log`.

**Comment by mswierzewski** [comment]
@mmagnuski 

> @mswierzewski różnicę dla dwóch wektorów robimy tak samo jak dla dwóch liczb: topografia_1 - topografia_2, 

Myślałem, o tym ale stwierdziłem, że to zbyt proste i pewnie jest do tego jakaś inna metoda...

Dzięki!

**Comment by pbarkowski** [comment]
Ok, pretenduję na najgłupsze pytanie 2017 roku: **czy topografię robimy dla elektrody Oz?** Pytam, ponieważ teoretycznie "tylko konieczne kroki prowadzące do wyświetlenia topografii" nie zawierają w sobie wyboru elektrody - tylko że wtedy mamy chyba bezsensowne wyniki :D

**Comment by mmagnuski** [comment]
@pbarkowski 
topografia to obraz aktywności dla wielu elektrod - w tym wypadku robimy dla wszystkich elektrod (tzn. po otrzymaniu macierzy psd dla wszystkich kanałów, uśredniamy dany zakres częstotliwości i mamy wektor do wyświetlenia topografii).
