### ISSUE TITLE
Projekty

### ISSUE THREAD

**Issue by mmagnuski** [mmagnuski/Analiza-Sygnalu-2017#3]
❗️ ostatni update: 09.02.2018 15:24 ❗️ 

W ramach projektu do wykonania jest analiza wielu plików z użyciem widma (`psd_welch`) albo też czasu-częstości (`tfr_morlet`). Możecie zrobić też porównanie erpów (przykład w  folderze z danymi decyzyjnymi) - jeżeli jednak robicie porównanie erpów, zróbcie również chociaż najprostsze porównanie częestotliwości. Analizę oddajecie w formie notebook'a. Macie czas do 20 lutego.

Musicie zdecydować się na to jaka analiza Was interesuje:
* zadanie / dane, których chcecie użyć
  - łatwo dostępne będą pliki z zadania **`Sternberg`**'a, które znacie z zajęć (`group analysis\sternberg`)
  - **`zadanie decyzyjne`** (prezentowane kolejne wskazówki dotyczące jakości diamentów, osoba badana wybiera lewy vs prawy diament gdy zdecyduje się, że któryś jest lepszy. Zwykle następuje to po pewnej ilości wskazówek - maksymalnie sześciu, bo tyle jest maksymalnie wskazówek na jeden trial) (`group analysis\decyzyjne`)
  - **`dane spoczynkowe`** (oczy otwarte oraz oczy zamknięte)
  - **`porządki liniowe`** (prezentowane kolejne wskazówki np `B > A`, `C > B` itp. na podstawie których osoba badana układa sobie w głowie porządek np `D > C > B > A`, przetrzymuje go w pamięci a następnie odpowiada na kilka pytań dotyczących bezpośrednich oraz przechodnich relacji z tego porządku)
* porównywane warunki:
  - dla danych z zadania Sternberga może to być porównanie dwóch wybranych loadów podczas przetrzymywania informacji w pamięci, albo dwóch prezentacji cyfr np. pierwszej i czwartej
  - możecie również zdecydować się na porównywanie więcej niż dwóch warunków korzystając z ANOVy (przykład dla erpów w `group analysis\decyzyjne\demo.ipynb`) albo regresji liniowej (np. zastanawiacie się czy wzrost alfy w obszarach potylicznych albo wzrost thety w obszarach czołowych jest liniowo zależny od obciążenia pamięci) - wtedy napiszcie tutaj i udostępnię Wam dodatkowe wskazówki
  - dla danych z zadania decyzyjnego możecie np. porównywać ostatnią i przedostatnią wskazówkę przed podjęciem decyzji aby zobaczyć jakiego rodzaju aktywność elektrofizjologiczna charakteryzuje podjęcie decyzji
* wielokrotne porównania i korekty
  - najprostsza opcja: redukcja całej przeszukiwanej przestrzeni tzn wybranie elektrod, czasu i częstotliwości zainteresowania i uśrednienie całej tej przestrzeni a następnie test statystyczny
  - częściowa redukcja np. uśredniamy częstotliwości zainteresowania, ale zostawiamy cały czas + wielokrotne porównania
  - przy wielokrotnych porównaniach możecie skorzystać z korekty Bonferroniego, FDR albo cluster-based

Najwyżej punktowane będą projekty korzystające z cluster-based korekty, co nie znaczy, że nie można zrobić projektu na 100% stosując prostsze metody - wielokrotne porównania a szczególnie cluster-based korekta będą dodatkowo punktowane, ale dodatkowo punktowane będą też wizualizacje czy bardziej zaawansowane podejścia statystyczne (ANOVA, regresja itp.).

Jeżeli chcecie uzyskać dostęp do datasetów, których nie ma jeszcze w `group analysis` - piszcie.

## ANOVA 
W wielu pracach dotyczących eeg ludzie stosują ANOVę mająz za czynniki np. przód - tył (głowy) oraz lewo-prawo, co moim zdaniem jest najczęściej niepotrzebne. Ale faktycznie, ANOVA jest stosowana bardzo często. W `group analysis\decyzyjne\demo.ipynb` jest przykład zastosowania anovy z powtarzanym pomiarem dla ERPów, polecam też poniższe linki:
    - [repeated measures anova - funkcja mne pythona](https://www.martinos.org/mne/stable/generated/mne.stats.f_mway_rm.html)
    - [przykład użycia anovy w mne](https://www.martinos.org/mne/stable/auto_tutorials/plot_stats_cluster_spatio_temporal_repeated_measures_anova.html)

## Regresja
W przypadku regresji będziecie musieli dopasować model. Dla sytuacji gdy macie niewiele porównań możecie wykorzystać bibliotekę statsmodels. Dla regresji wewnątrz osób najlepiej jak dopasujecie dla każdej osoby oddzielnie model regresji i następnie na poziomie grupy zrobicie test t (względem zera) parametrów modelu. Wiem że to brzmi tajemniczo, ale to dosyć często stosowana analiza dwukrokowa - jeżeli ktoś chce się z tym zmierzyć - napiszcie, postaram się wrzucić przykład w postaci notebook'a.

## Parametry TFR
Na początek możecie stosować te same parametry co na zajęciach. Postaram się przy ładowaniu plików podrzucić do każdego datasetu plik z podstawowymi informacjami albo te informacje wrzucić do notebook'a. Tam wspomnę o polecanych parametrach. Generalnie - jeżeli chcecie badać wysokie częstotliwości, możecie `freq` ustawić odpowiednio wysoko (np. 35 - 59, z odstępem co 2 Hz), a wtedy możecie sobie pozwolić na wyższe `n_cycles` np. dla wszystkich częstotliwości 10 cykli. Wtedy dla 35 Hz macie długość falki 10/35 s czyli trochę ponad 280 ms a dla 59 Hz: 10/59 czyli ok. 170 ms. Możecie się ogólnie starać aby Wasze falki nie były dłuższe niż 2/3 zakresu baseline'u a najlepiej nie dłuższe niż 50% tego czasu.

## Deadline'y
Możemy się umówić tak, że prace wysłane do 17 lutego mają szansę na feedback (w ciągu kilku dni). W przypadku oddaniu projektu do 17, po dostaniu feedbacku będziecie mieli kilka dni (max 6-7) na poprawienie pracy, jeżeli taka będzie Wasza wola.

## Które pliki analizować
Każdy z datasetów zawiera tylko niektóre pliki z oryginalnego badania abyście nie czekali zbyt długo na wczytywanie/przetwarzanie kolejnych plików. Nawet mimo to i tak najlepiej będzie jeżeli nie będziecie korzystać ze wszystkich plików w danym folderze, a wybierzecie tylko np. 80% udostępnionych dla danego datasetu plików. Wtedy każdy student analizujący dany dataset powinien mieć nieco inny zestaw plików.

**Comment by pbarkowski** [comment]
Ok, więc może ja zacznę. Przyznam, że z ostatniego tutoriala na zajęciach zrobiłem 45/60 minut, dlatego jeśli coś jest na filmie później, a ja tu poruszam ten temat - sorry.

Mikołaju:

0. mamy dwa tygodnie?
1. możesz wrzucić na dropboxa pliki (albo lepiej od razu katalogi) z innych procedur? **`zadania decyzyjne`** i **`porządki liniowe`** brzmią bardzo ciekawie :)
2. podpowiesz coś więcej na temat ANOVy? w pracach na temat eeg pojawia się praktycznie wszędzie, a na żadnych zajęciach chyba tego nie mieliśmy?
3. w przypadku regresji liniowej musimy po prostu przeanalizować odpowiednią ilość warunków i zmodyfikować wykres skrzypcowy z ostatniego notebooka? lub nawet poprzez dodanie linii regresji do takiego wykresu skrzypcowego z większa ilością przypadków?
4. analogicznie decoding - chętnie dowiedziałbym się więcej, a nie mam pojęcia jak ugryźć ten temat. czy nie omawiając tego na zajęciach, jest to w naszym zasięgu?
5. jeśli decydowałbym się na `tfr_morlet`, to czy nasze zmienne: `freq` oraz `n_cycles` stosujemy w takiej postaci jak w ostatnim notebooku, czy zależy to od procedury/plików/czegoś nienazwanego? analogiczne pytanie o baseline - jak w najnowszym notebooku?
6. zakładając niemożliwe - czyli wysłanie nie w ostatni dzień terminu - można liczyć na feedback i/lub poprawienie wskazanych przez Ciebie elementów dla ewentualnej poprawy wyniku?

**Comment by mmagnuski** [comment]
Hej, sorry za delay w odpisywaniu.

Odpowiadam po kolei:

0. Tak,  przy czym zrobię raczej tak, że macie czas do 20 lutego (nie 14) - bo faktycznie nie macie jeszcze dostępu do datasetów.
1. Tak, postaram się to wszystko zrobić dziś. Niektóre zadania będą wymagały specjalnego wczytywania. Wtedy do folderu wrzucę `demo.ipynb` pokazujące jak wczytać jeden plik i np. wybrać odpowiednie epoki.
2. W wielu pracach dotyczących eeg ludzie stosują ANOVę mająz za czynniki np. przód - tył (głowy) oraz lewo-prawo, co moim zdaniem jest najczęściej niepotrzebne. Ale faktycznie, ANOVA jest stosowana bardzo często. Wrzucę Wam przykład dot anovy z powtarzanym pomiarem, na razie oferuję poniższe linki:
    - [repeated measures anova - funkcja mne pythona](https://www.martinos.org/mne/stable/generated/mne.stats.f_mway_rm.html)
    - [przykład użycia anovy w mne](https://www.martinos.org/mne/stable/auto_tutorials/plot_stats_cluster_spatio_temporal_repeated_measures_anova.html)
3. oprócz wykresu w przypadku regresji będziecie musieli dopasować model. Dla sytuacji gdy macie niewiele porównań możecie wykorzystać bibliotekę statsmodels. Dla regresji wewnątrz osób najlepiej jak dopasujecie dla każdej osoby oddzielnie model regresji i następnie na poziomie grupy zrobicie test t (względem zera) parametrów modelu. Wiem że to brzmi tajemniczo, ale to dosyć często stosowana analiza dwukrokowa - postaram się w tym tygodniu wrzucić przykład (w postaci notebook'a).
4. Może faktycznie nie ma sensu się za to zabierać, skoro nie przerabiamy tego na zajęciach. Mogę wrzucić przykład, ale w ostatniej kolejności. Jeżeli interesuje Cię decoding - będę go stosował (między innymi) w moim projekcie oraz w projekcie Leona Ciechanowskiego stosujemy decoding; możemy się dogadać mailowo jakbyś chciał pouczestniczyć.
5. Na początek możecie stosować te same parametry co na zajęciach. Postaram się przy ładowaniu plików podrzucić do każdego datasetu plik z podstawowymi informacjami albo te informacje wrzucić do notebook'a. Tam wspomnę o polecanych parametrach. Generalnie - jeżeli chcecie badać wysokie częstotliwości, możecie `freq` ustawić odpowiednio wysoko (np. 35 - 59, z odstępem co 2 Hz), a wtedy możecie sobie pozwolić na wyższe `n_cycles` np. dla wszystkich częstotliwości 10 cykli. Wtedy dla 35 Hz macie długość falki 10/35 s czyli trochę ponad 280 ms a dla 59 Hz: 10/59 czyli ok. 170 ms. Możecie się ogólnie starać aby Wasze falki nie były dłuższe niż 2/3 zakresu baseline'u a najlepiej nie dłuższe niż 50% tego czasu.
6. Możemy się umówić tak, że prace wysłane do 17 lutego mają szansę na feedback (w ciągu kilku dni). W przypadku oddaniu projektu do 17, po dostaniu feedbacku będziecie mieli kilka dni (max 6-7) na poprawienie pracy, jeżeli taka będzie Wasza wola.

Powyższe uwagi uporządkuję i wrzucę do informacji powyżej (tzn do pierwszego posta) wkrótce.

**Comment by mmagnuski** [comment]
(drobny update - wrzucam pliki dopiero teraz)
wkrótce napiszę więcej

**Comment by pbarkowski** [comment]
Mikołaj, pliki ze Sternberga pomieszały się z dawnymi - patrząc po dacie uploadu:

![image](https://user-images.githubusercontent.com/23636909/35921024-d15ff1dc-0c19-11e8-904d-82a8c09e3ccb.png)

Żeby uniknąć błędów, może lepiej stworzyć osoby podfolder lub osobny link do innego dropboxa?

**Comment by mmagnuski** [comment]
Racja, usunę te starsze, są niepotrzebne.

**Comment by pbarkowski** [comment]
Hej, ponieważ mi baaardzo zależy na szybkim oddaniu projektu, powoli kończę na tym co jest w tym momencie (procedurze Sternberg'a) i postaram się wysłać w weekend. 

Dlatego - jeżeli chodzi oczywiście o mnie - nie ma potrzeby wrzucania pozostałych plików, szczególnie jeśli musiałbyś tworzyć dodatkowe notebooki. Proponuję poczekać, czy ktoś inny się po nie zgłosi, i wówczas ewentualny upload ;)

**Comment by mmagnuski** [comment]
Właśnie kończę notebook do decyzyjnych z przykładem anovy. :P 
Dane są w `group analysis\decyzyjne`.

**Comment by mmagnuski** [comment]
Zrobiłem tutaj oraz pośród plików lekki porządek, zupdate'owane informacje na górze.
@pbarkowski - zaraz odpowiem na Twojego maila.

**Comment by olaartych** [comment]
Mikołaj, przepraszam jeśli mi to gdzieś umknęło ale możesz wstawić "legendę" do loadów dla Sterneberga?

**Comment by mmagnuski** [comment]
load_2 to dwie cyfry przetrzymywane w pamięci, load_3 - trzy cyfry itd.

**Comment by olaartych** [comment]
jasne, dziękuję :)

**Comment by Fostaszewski** [comment]
Jakiś pomysł skąd ten error i jak go naprawić? google mi średnio pomógł:(

![image](https://user-images.githubusercontent.com/24207207/36327023-727d5466-135d-11e8-8b22-f679114d5c0a.png)

**Comment by mmagnuski** [comment]
Masz widocznie stare mypy. Jak i kiedy je instalowałeś? Możesz odinstalować przez `pip uninstall mypy` a następnie zainstalować tak jak sugeruje dokument dotyczący instalacji.
Swoją drogą zmienię w niezbyt odległej przyszłości nazwę bo `pip install mypy` instaluje co innego, co zmyliło już kilka osób. Trzeba instalować z git'a - tak jak w dokumencie dot. instalacji.

**Comment by diathermy** [comment]
@mmagnuski Mikołaj, jak tytułować mejle z projektem?

**Comment by BarbZielinska** [comment]
Hej, walczę z błędem "SyntaxError: positional argument follows keyword argument" pojawiającym się przy kodzie sns.violinplot (który na tutku Ty też, Mikołaju, miałeś, ale udało Ci się go obejść) na różne sposoby - próbowałam już usuwać te infs i NaNs, ale w dalszym ciągu komunikat krzyczy: ValueError: array must not contain infs or NaNs. Cóż uczynić?

![image](https://user-images.githubusercontent.com/23638226/36356842-4707bcd0-14f8-11e8-95fc-093d8c3bb499.png)
![image](https://user-images.githubusercontent.com/23638226/36356856-63ffd390-14f8-11e8-8c27-210705758370.png)
![image](https://user-images.githubusercontent.com/23638226/36356860-6f36638c-14f8-11e8-9f0a-e11221d30526.png)

**Comment by BarbZielinska** [comment]
Hej, staram się uporać z tym błędem:
![image](https://user-images.githubusercontent.com/23638226/36357317-8333f3aa-14fc-11e8-8b53-42209173a09d.png)
![image](https://user-images.githubusercontent.com/23638226/36357324-94e8ad84-14fc-11e8-993e-50b8380dc957.png)

próbowałam użyć komend, które mają za zadanie usunąć tzw infs i NaNs, ale na niewiele się to zdało...
pojawia się wtedy błąd taki, jak u Ciebie, Mikołaju, na tutorialu. Zastanawiam się, czy chodzi o te wartości avg_l2 i avg_l4, niezaktualizowaną bibliotekę, czy jaką, że tak to ujmę, cholerę... :P

**Comment by mmagnuski** [comment]
@diathermy Najlepiej tak aby w tytule maila było 'projekt'.
@BarbZielinska W komunikacie błędu masz napisane że w danych nie może być wartości `NaN` (not a number) ani `inf` (infinity). Wyświetl sobie co jest w `avg_l2` albo `avg_l4` - w którymś z nich prawdopodobnie są wartości typu `NaN`. Nie powinno ich tam raczej być, ale trudno mi powiedzieć więcej, bez wiedzy o tym co robiłaś wcześniej.
Nie pamiętam jaki błąd jest na tutorialu, ale może `avg_l2` i `avg_l4` mają różną liczbę nan'ów? Wtedy będzie błąd, bo po usunięciu nan'ów wektory będą różnej długości.

**Comment by BarbZielinska** [comment]
Czyli muszę usunąć Infs i NaNs? Jest ich sporo:
![image](https://user-images.githubusercontent.com/23638226/36375619-3e8b1570-1570-11e8-9d74-018990f16e9d.png)
![image](https://user-images.githubusercontent.com/23638226/36375630-4cbb03b2-1570-11e8-94bb-476efe617c23.png)

Chociaż udało mi się wcześniej je usunąć za pomocą komunikatu:
np.isnan(xx).any()
np.isnan(yy).any()
np.isinf(xx).any()
np.isinf(yy).any()

xx = np.nan_to_num(xx)
yy = np.nan_to_num(yy

to i tak nie załatwiło to sprawy niewyświetlania się figur load2 i load4 przy użyciu komendy sns.violinplot.
:(

**Comment by pbarkowski** [comment]
@BarbZielinska 
przypadkiem wyżej pokazałaś warning "(...) divide by zero (...)" - więc wydaje mi się, że problem leży trochę wyżej, a ten Inf i NaN to są konsekwencje tego - może pokaż zawartość `tfrs_l2` i `tfrs_l4`?

**Comment by BarbZielinska** [comment]
Jasne, już pokazuję.
![image](https://user-images.githubusercontent.com/23638226/36376377-2f77e72c-1573-11e8-832e-ebe7368fc33d.png)
![image](https://user-images.githubusercontent.com/23638226/36376389-3c6d4832-1573-11e8-8d22-340213493b71.png)
![image](https://user-images.githubusercontent.com/23638226/36376403-48d594da-1573-11e8-8086-9404faab25c2.png)
![image](https://user-images.githubusercontent.com/23638226/36376415-52cea6f2-1573-11e8-91f7-07a710284d87.png)

**Comment by pbarkowski** [comment]
Na pierwszy rzut oka powinno wszystko działać. Dwa pytania:
1. aktualizowałaś mne-python?
2. pierwszy zrzut - komórka pod tą [26] wydaje się nieodpalona - czy gdzieś wyżej odpalałaś coś takiego samego? domyślam się że tak, ale chcę wykluczyć wszystkie możliwości :)

**Comment by BarbZielinska** [comment]
Aj, nie zauważyłam, że ten screen taki nieładny wyszedł, ale tak, odpalałam i z tym jest w porządku. 
Czy wersja mne-0.15.2 jest odpowiednia?

**Comment by sylwiataczanowska** [comment]
![runtime](https://user-images.githubusercontent.com/23698395/36377709-62890f74-1578-11e8-9b20-cf97e8122490.png)

Czy ta informacja jest o błędzie czy można ją zignorować? Poprosiłam o pomoc google, radzą coś pozmieniać, ale za bardzo nie wiem jak.

**Comment by pbarkowski** [comment]
Ja używam 0.16.dev0, ale nie mam pojęcia czy to powoduje błąd - chyba trzeba poczekać na Mikołaja żeby mieć pewność.

@sylwiataczanowska - chyba będziesz miała dokładnie do samo co Basia w tym momencie

**Comment by BarbZielinska** [comment]
Dziękuję Ci Bartku, już śmiga! <3

**Comment by BarbZielinska** [comment]
@sylwiataczanowska w cmdrze najpierw wpisz conda, a potem pip install mne --upgrade

**Comment by sylwiataczanowska** [comment]
w sumie ta korekta nie chce się aplikować
![runtime2](https://user-images.githubusercontent.com/23698395/36377933-267eceaa-1579-11e8-961e-e3fa50995c39.png)

@BarbZielinska  spróbuje tego co mówisz

**Comment by sylwiataczanowska** [comment]
Zrobiłam tę aktualizację, ale nadal to samo pokazuje :(

**Comment by pbarkowski** [comment]
poradzę bardzo znaną metodą: spróbuj wyłączyć i włączyć od nowa, włącznie z nowym wierszem poleceń ;) jeśli u @BarbZielinska to pomogło, to musi u Ciebie pójść. Ewentualnie po prostu sprawdź, czy faktycznie masz nową wersję zaimportowaną (tę po aktualizacji).

**Comment by sylwiataczanowska** [comment]
Aktualizacja nie pomogła, ale za to pomocny okazał się niezawodny sposób, który pomaga przy każdym projekcie czyli odinstalowanie mne i mypy i zainstalowanie ich od początku :)

**Comment by mmagnuski** [comment]
@sylwiataczanowska @BarbZielinska
Wydaje mi się że to nie powinna być kwestia mne ani mypy bądź ich wersji.
Jestem prawie pewien, że zastosowałyście `apply_baseline` więcej niż raz (pewnie przez przypadek, a może i bez dostrzeżenia tego). Po pierwszym baseline correction średnia w oknie Waszego baseline'u będzie wynosić 0 (`baseline - baseline = 0`). Wtedy gdy zastosujecie baseline correction ponownie - wystąpi dzielenie przez zero, ponieważ baseline wyniesie 0 (aby obliczyć procentową zmianę wartości względem baseline'u liczymy: `(wartość - baseline) / baseline`). Dziwne tylko, że nie dla wszystkich punktów macie NaN'y - ale to pewnie błędy związane z niedokładnością numeryczną...

**Comment by diathermy** [comment]
@mmagnuski  
Kiedy możemy się spodziewać obiecanego feedbacku z możliwością do porawy dla osób, które wysłały pracę do 17.02?

**Comment by mmagnuski** [comment]
poniedziałek/wtorek, sorry że tyle to trwa, ale jeżeli ktoś potrzebuje można jeszcze wysyłać projekty (max do końca lutego)

**Comment by mmagnuski** [comment]
finito
